[workspace]
members = [
  "sudo",
  "test-binaries",
  "lib/sudo-cli",
  "lib/sudo-common",
  "lib/sudo-cutils",
  "lib/sudo-env",
  "lib/sudo-system",
  "lib/sudoers",
  "lib/sudo-defaults",
  "lib/sudo-pam-sys",
  "lib/sudo-pam",
  "lib/sudo-exec",
  "lib/sudo-log",
]
default-members = ["sudo"]

[workspace.package]
version = "0.1.0-alpha.1"
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://github.com/memorysafety/sudo-rs"
homepage = "https://github.com/memorysafety/sudo-rs"
publish = true

[workspace.dependencies]
clap = "4.0.32"
libc = "0.2.142"
thiserror = "1.0.38"
glob = "0.3.1"
sha2 = "0.10.6"
digest = "0.10.6"
signal-hook = "0.3.15"
log = "0.4.17"
syslog = "6.0.1"
env_logger = "0.9.3"

# Test only dependencies
pretty_assertions = "1.3.0"
tempfile = "3.5.0"

# Build time dependencies
bindgen = "0.63.0"

sudo-cli = { version = "0.1.0-alpha.1", path = "./lib/sudo-cli" }
sudo-env = { version = "0.1.0-alpha.1", path = "./lib/sudo-env" }
sudo-pam = { version = "0.1.0-alpha.1", path = "./lib/sudo-pam" }
sudo-system = { version = "0.1.0-alpha.1", path = "./lib/sudo-system" }
sudo-pam-sys = { version = "0.1.0-alpha.1", path = "./lib/sudo-pam-sys" }
sudo-cutils = { version = "0.1.0-alpha.1", path = "./lib/sudo-cutils" }
sudo-common = { version = "0.1.0-alpha.1", path = "./lib/sudo-common" }
sudo-defaults = { version = "0.1.0-alpha.1", path = "./lib/sudo-defaults" }
sudo-exec = { version = "0.1.0-alpha.1", path = "./lib/sudo-exec" }
sudo-log = { version = "0.1.0-alpha.1", path = "./lib/sudo-log" }
sudoers = { version = "0.1.0-alpha.1", path = "./lib/sudoers" }

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1
opt-level = "s"
