[workspace]
members = [
  "sudo",
  "su",
]
default-members = ["sudo"]

resolver = "2"

[workspace.package]
version = "0.1.0-alpha.1"
license = "Apache-2.0 OR MIT"
edition = "2021"
repository = "https://github.com/memorysafety/sudo-rs"
homepage = "https://github.com/memorysafety/sudo-rs"
publish = true

[workspace.dependencies]
libc = "0.2.139"
glob = "0.3.1"
signal-hook = "0.3.15"
signal-hook-registry = "1.4.1"
log = "0.4.17"
env_logger = { version = "0.9.3", default-features = false }

sudo = { version = "0.1.0-alpha.1", path = "./sudo" }

# Test only dependencies
pretty_assertions = "1.3.0"
tempfile = "3.5.0"

[profile.release]
strip = "debuginfo"
lto = true
opt-level = "s"
